- name: Set the kind cluster context and install the helm chart
  shell: "kubectl config use-context kind-{{ kind_cluster_name }} && helm upgrade --install pizza-express-chart ../pizza-express-chart/ && sleep 8"
